from burp import IBurpExtender, IHttpListener, ITab, IMessageEditorController, IHttpRequestResponse, IHttpService, IParameter
from javax.swing import JFrame, JPanel, JTable, JScrollPane, JTextArea, table, BoxLayout, JTabbedPane, JSplitPane, JLabel, JButton, SwingUtilities, JCheckBox, JOptionPane, JTextField
from javax.swing.table import DefaultTableCellRenderer
from java.awt import BorderLayout, Color, Dimension, FlowLayout, Font
from java.awt.event import MouseAdapter, KeyEvent, KeyAdapter, ActionListener
from java.lang import Runnable
from java.net import URL
from urllib import quote, unquote
import random
import json
import re
import base64
import fnmatch


class MyMouseListener(MouseAdapter):
    def __init__(self, table, extender):
        self.table = table
        self.extender = extender

    def mouseClicked(self, e):
        row = self.table.getSelectedRow()
        if row != -1:
            # Perform the desired action when the user clicks on a row
            self.extender._requestViewer.setMessage(self.extender.data_requests[row], True)
            self.extender._responseViewer.setMessage(self.extender.data_responses[row], False)

class MyKeyListener(KeyAdapter):
    def __init__(self, table, extender):
        self.table = table
        self.extender = extender

    def keyPressed(self, e):
        if e.getKeyCode() == KeyEvent.VK_UP or e.getKeyCode() == KeyEvent.VK_DOWN:
            # Use invokeLater to ensure row is selected before getting it
            SwingUtilities.invokeLater(UpdateViewerRunnable(self.table, self.extender))

class UpdateViewerRunnable(Runnable):
    def __init__(self, table, extender):
        self.table = table
        self.extender = extender
    
    def run(self):
        row = self.table.getSelectedRow()
        if row != -1:
            self.extender._requestViewer.setMessage(self.extender.data_requests[row], True)
            self.extender._responseViewer.setMessage(self.extender.data_responses[row], False)

class ClearButtonListener(ActionListener):
    def __init__(self, extender):
        self.extender = extender
    
    def actionPerformed(self, e):
        self.extender.clearResults()

class SettingsButtonListener(ActionListener):
    def __init__(self, extender):
        self.extender = extender

    def actionPerformed(self, e):
        self.extender.openSettingsDialog()

class TooltipRenderer(DefaultTableCellRenderer):
    def __init__(self, extender):
        DefaultTableCellRenderer.__init__(self)
        self.extender = extender

    def getTableCellRendererComponent(self, tbl, value, isSelected, hasFocus, row, column):
        component = DefaultTableCellRenderer.getTableCellRendererComponent(self, tbl, value, isSelected, hasFocus, row, column)
        try:
            model_row = tbl.convertRowIndexToModel(row)
            if model_row < len(self.extender.data_tooltips) and self.extender.data_tooltips[model_row]:
                component.setToolTipText(self.extender.data_tooltips[model_row])
            else:
                component.setToolTipText(None)
        except Exception:
            component.setToolTipText(None)
        return component


class BurpExtender(IBurpExtender, IHttpListener, ITab, IMessageEditorController, IHttpService, IHttpRequestResponse):
    
    def __init__(self):
        self.data = []
        self.data_requests = []
        self.data_responses = []
        self.panel = None
        self.tableModel = None
        self.id = 0
        self.modified_cookie_header = []
        self.splitpane = JSplitPane(JSplitPane.VERTICAL_SPLIT)
        self.myTable = JTable()
        self._requestViewer = None
        self._responseViewer = None
        self.editor_panel = JPanel(BorderLayout())
        self.stats_label = None
        self.tested_urls = set()   # Track tested original URLs to avoid re-testing
        self.reported_urls = set()  # Track tested payload URLs to avoid duplicate findings
        self.data_tooltips = []     # Per-row tooltip text (None if no tooltip)
        # Track requests generated by this extension so we can ignore them
        self.our_requests = set()
        self.payload = "ggg2\"ggg3>ggg4<"
        # Double-URL-encoded form of the special chars: server decodes once -> %22 %3E %3C
        # server decodes twice -> " > <  (WAF bypass)
        self.payload_double_encoded = "ggg2%22ggg3%3Eggg4%3C"
        self.settings = {
            "scan_post": True,
            "detect_json": False,
            "inject_cookie": True,
            "inject_header": True,
            "prefer_non_session_cookies": False,
            "excluded_cookies": "",
            "scope_filter": "",
            "inject_base64": True,
            "per_param_testing": False,
            "inject_known_headers": True,
            "double_encode": False,
            "inject_all_fragments": False,
            "inject_path_segments": True,
            "path_level_dedup": True,
        }

    def getTabCaption(self):
        return "isXSS"

    def getUiComponent(self):
        if not self.panel:  # Only create panel once
            self.panel = JPanel(BorderLayout())

            # Top toolbar panel with statistics and controls
            toolbar = JPanel(FlowLayout(FlowLayout.LEFT, 10, 5))
            toolbar.setBackground(Color(240, 240, 240))
            
            # Statistics label
            self.stats_label = JLabel("Findings: 0")
            self.stats_label.setFont(Font("Dialog", Font.BOLD, 12))
            toolbar.add(self.stats_label)
            
            # Clear button
            clear_button = JButton("Clear Results")
            clear_button.addActionListener(ClearButtonListener(self))
            toolbar.add(clear_button)

            # Settings button
            settings_button = JButton(u"\u2699 Settings")
            settings_button.addActionListener(SettingsButtonListener(self))
            toolbar.add(settings_button)
            
            self.panel.add(toolbar, BorderLayout.NORTH)

            # Table UI
            panel_table = JPanel(BorderLayout())
            head = ['ID', 'Method', 'URL', 'Reflected Characters']
            self.tableModel = table.DefaultTableModel(self.data, head)
            
            self.myTable.setModel(self.tableModel) 
            self.myTable.setAutoCreateRowSorter(True)
            self.myTable.setRowHeight(25)
            self.myTable.setShowGrid(True)
            self.myTable.setGridColor(Color(220, 220, 220))
            
            # Adjust column widths
            self.myTable.autoResizeMode = JTable.AUTO_RESIZE_ALL_COLUMNS
            self.myTable.columnModel.getColumn(0).preferredWidth = 50
            self.myTable.columnModel.getColumn(0).setMaxWidth(80)
            self.myTable.columnModel.getColumn(1).preferredWidth = 80
            self.myTable.columnModel.getColumn(1).setMaxWidth(100)
            self.myTable.columnModel.getColumn(2).preferredWidth = 500
            self.myTable.columnModel.getColumn(3).preferredWidth = 150
            self.myTable.columnModel.getColumn(3).setMaxWidth(200)

            tooltip_renderer = TooltipRenderer(self)
            for i in range(4):
                self.myTable.columnModel.getColumn(i).setCellRenderer(tooltip_renderer)

            scrollPane = JScrollPane(self.myTable)
            panel_table.add(scrollPane, BorderLayout.CENTER)

            self.myTable.addMouseListener(MyMouseListener(self.myTable, self))
            self.myTable.addKeyListener(MyKeyListener(self.myTable, self))

            # Split pane for table and request/response viewers
            self.splitpane.setTopComponent(panel_table)
            self.splitpane.setBottomComponent(self.editor_panel)
            self.splitpane.setDividerLocation(300)
            self.splitpane.setResizeWeight(0.4)
            
            self.panel.add(self.splitpane, BorderLayout.CENTER)
        
        return self.panel
    
    def updateTable(self):
        self.tableModel.setDataVector(self.data, ['ID', 'Method', 'URL', 'Reflected Characters'])
        # Reapply column settings after data update
        self.myTable.columnModel.getColumn(0).preferredWidth = 50
        self.myTable.columnModel.getColumn(0).setMaxWidth(80)
        self.myTable.columnModel.getColumn(1).preferredWidth = 80
        self.myTable.columnModel.getColumn(1).setMaxWidth(100)
        self.myTable.columnModel.getColumn(2).preferredWidth = 500
        self.myTable.columnModel.getColumn(3).preferredWidth = 150
        self.myTable.columnModel.getColumn(3).setMaxWidth(200)
        tooltip_renderer = TooltipRenderer(self)
        for i in range(4):
            self.myTable.columnModel.getColumn(i).setCellRenderer(tooltip_renderer)
        # Update statistics
        if hasattr(self, 'stats_label'):
            self.stats_label.setText("Findings: " + str(len(self.data)))
    
    def clearResults(self):
        self.data = []
        self.data_requests = []
        self.data_responses = []
        self.tested_urls = set()
        self.reported_urls = set()
        self.data_tooltips = []
        self.our_requests = set()
        self.id = 0
        self.updateTable()
        self._requestViewer.setMessage(None, True)
        self._responseViewer.setMessage(None, False)

    def openSettingsDialog(self):
        settings_panel = JPanel()
        settings_panel.setLayout(BoxLayout(settings_panel, BoxLayout.Y_AXIS))

        # Scope filter
        scope_label = JLabel("Scope filter (comma-separated glob patterns, e.g. *.example.com):")
        scope_field = JTextField(self.settings.get("scope_filter", ""), 40)
        scope_field.setMaximumSize(scope_field.getPreferredSize())

        post_checkbox = JCheckBox("Enable POST request testing", self.settings.get("scan_post", True))
        json_checkbox = JCheckBox("Enable findings for JSON responses", self.settings.get("detect_json", False))
        base64_checkbox = JCheckBox("Decode base64 parameter values, inject payload, and re-encode", self.settings.get("inject_base64", True))
        cookie_checkbox = JCheckBox("Inject payload into one random cookie per request", self.settings.get("inject_cookie", True))
        session_cookie_checkbox = JCheckBox("  Prefer non-session cookies (skip known session cookie names)", self.settings.get("prefer_non_session_cookies", False))
        header_checkbox = JCheckBox("Inject payload into one random non-essential header per request", self.settings.get("inject_header", True))

        # Cookie exclusion text field
        excluded_cookies_label = JLabel("  Cookies to never inject into (comma-separated):")
        excluded_cookies_field = JTextField(self.settings.get("excluded_cookies", ""), 30)
        excluded_cookies_field.setMaximumSize(excluded_cookies_field.getPreferredSize())

        settings_panel.add(scope_label)
        settings_panel.add(scope_field)
        settings_panel.add(post_checkbox)
        settings_panel.add(json_checkbox)
        settings_panel.add(base64_checkbox)
        settings_panel.add(cookie_checkbox)
        settings_panel.add(session_cookie_checkbox)
        settings_panel.add(excluded_cookies_label)
        settings_panel.add(excluded_cookies_field)
        per_param_checkbox = JCheckBox("Test each parameter individually (per-param mode, not all-at-once)", self.settings.get("per_param_testing", False))
        known_headers_checkbox = JCheckBox("Always inject into high-value headers (User-Agent, Referer, X-Forwarded-For, Origin, etc.)", self.settings.get("inject_known_headers", True))
        double_encode_checkbox = JCheckBox("Test double URL-encoded payload variants (WAF bypass)", self.settings.get("double_encode", False))
        all_fragments_checkbox = JCheckBox("Inject payload into hash fragment on all requests (default: only if fragment already exists)", self.settings.get("inject_all_fragments", False))
        path_segments_checkbox = JCheckBox("Inject payload into dynamic URL path segments (numeric IDs, UUIDs, slugs with digits)", self.settings.get("inject_path_segments", True))
        path_dedup_checkbox = JCheckBox("Deduplicate by path only, ignore query parameters (reduces re-testing paginated endpoints)", self.settings.get("path_level_dedup", True))

        settings_panel.add(header_checkbox)
        settings_panel.add(per_param_checkbox)
        settings_panel.add(known_headers_checkbox)
        settings_panel.add(double_encode_checkbox)
        settings_panel.add(all_fragments_checkbox)
        settings_panel.add(path_segments_checkbox)
        settings_panel.add(path_dedup_checkbox)

        choice = JOptionPane.showConfirmDialog(
            self.panel,
            settings_panel,
            "isXSS Settings",
            JOptionPane.OK_CANCEL_OPTION,
            JOptionPane.PLAIN_MESSAGE
        )

        if choice == JOptionPane.OK_OPTION:
            self.settings["scope_filter"] = scope_field.getText().strip()
            self.settings["scan_post"] = post_checkbox.isSelected()
            self.settings["detect_json"] = json_checkbox.isSelected()
            self.settings["inject_base64"] = base64_checkbox.isSelected()
            self.settings["inject_cookie"] = cookie_checkbox.isSelected()
            self.settings["prefer_non_session_cookies"] = session_cookie_checkbox.isSelected()
            self.settings["excluded_cookies"] = excluded_cookies_field.getText().strip()
            self.settings["inject_header"] = header_checkbox.isSelected()
            self.settings["per_param_testing"] = per_param_checkbox.isSelected()
            self.settings["inject_known_headers"] = known_headers_checkbox.isSelected()
            self.settings["double_encode"] = double_encode_checkbox.isSelected()
            self.settings["inject_all_fragments"] = all_fragments_checkbox.isSelected()
            self.settings["inject_path_segments"] = path_segments_checkbox.isSelected()
            self.settings["path_level_dedup"] = path_dedup_checkbox.isSelected()

    def _pick_random_cookie_param(self, parameters):
        cookie_params = [p for p in parameters if p.getType() == IParameter.PARAM_COOKIE]
        if not cookie_params:
            return None

        # Always apply user-defined hard exclusions
        user_excluded = set()
        user_excluded_str = self.settings.get("excluded_cookies", "")
        if user_excluded_str:
            user_excluded = set(n.strip().lower() for n in user_excluded_str.split(",") if n.strip())

        eligible = [p for p in cookie_params if p.getName().lower() not in user_excluded]
        if not eligible:
            return None

        # When toggle is on, prefer non-session cookies within the eligible set
        if self.settings.get("prefer_non_session_cookies", True):
            common_session_names = set([
                "session", "sessionid", "phpsessid", "jsessionid", "asp.net_sessionid", "sid", "connect.sid"
            ])
            non_session = [p for p in eligible if p.getName().lower() not in common_session_names]
            if non_session:
                return random.choice(non_session)

        return random.choice(eligible)

    def _pick_random_header_name(self, headers):
        # Skip request line; only consider non-essential headers
        excluded = set([
            "host", "cookie", "content-length", "content-type", "transfer-encoding",
            "authorization", "proxy-authorization", "connection", "accept-encoding"
        ])
        candidates = []
        for h in headers[1:]:
            if ":" not in h:
                continue
            name = h.split(":", 1)[0].strip()
            if not name:
                continue
            if name.lower() in excluded:
                continue
            candidates.append(name)

        if not candidates:
            return None
        return random.choice(candidates)

    def _replace_header_value(self, request_bytes, header_name, new_value, http_service):
        if not header_name:
            return request_bytes

        try:
            req_info = self._helpers.analyzeRequest(http_service, request_bytes)
            headers = list(req_info.getHeaders())
            body_offset = req_info.getBodyOffset()
            body = request_bytes[body_offset:] if body_offset != -1 else None

            for i in range(1, len(headers)):
                if ":" not in headers[i]:
                    continue
                name, _ = headers[i].split(":", 1)
                if name.strip().lower() == header_name.lower():
                    headers[i] = name + ": " + new_value
                    break

            return self._helpers.buildHttpMessage(headers, body)
        except Exception:
            return request_bytes

    def _add_or_replace_header(self, request_bytes, header_name, new_value, http_service):
        """Add the header if not present in the request, otherwise replace its value."""
        if not header_name:
            return request_bytes
        try:
            req_info = self._helpers.analyzeRequest(http_service, request_bytes)
            headers = list(req_info.getHeaders())
            body_offset = req_info.getBodyOffset()
            body = request_bytes[body_offset:] if body_offset != -1 else None
            found = False
            for i in range(1, len(headers)):
                if ":" not in headers[i]:
                    continue
                name, _ = headers[i].split(":", 1)
                if name.strip().lower() == header_name.lower():
                    headers[i] = name + ": " + new_value
                    found = True
                    break
            if not found:
                headers.append(header_name + ": " + new_value)
            return self._helpers.buildHttpMessage(headers, body)
        except Exception:
            return request_bytes

    def _inject_payload_into_json(self, json_obj):
        """Recursively inject payload into all string values in a JSON structure."""
        if isinstance(json_obj, dict):
            return {k: self._inject_payload_into_json(v) for k, v in json_obj.items()}
        elif isinstance(json_obj, list):
            return [self._inject_payload_into_json(item) for item in json_obj]
        elif isinstance(json_obj, basestring):
            return self.payload
        else:
            return json_obj

    def _get_json_injected_value(self, param_value):
        """
        Detect if param_value (or its URL-decoded form) is a JSON object or array.
        If so, inject payload into all string values, re-serialize, and return
        the injected JSON string (unencoded). Returns None if not JSON.
        """
        try:
            decoded = unquote(param_value)
            # Try URL-decoded first, then raw (avoids duplicate attempt when no encoding)
            candidates = [decoded] if decoded != param_value else []
            candidates.append(param_value)
            for candidate in candidates:
                try:
                    json_obj = json.loads(candidate)
                    if not isinstance(json_obj, (dict, list)):
                        continue
                    injected = self._inject_payload_into_json(json_obj)
                    return json.dumps(injected, separators=(',', ':'))
                except ValueError:
                    continue
            return None
        except Exception:
            return None

    def _host_matches_scope(self, host):
        """Return True if host matches any of the comma-separated scope glob patterns,
        or if no scope filter is configured (allow all)."""
        scope_filter = self.settings.get("scope_filter", "").strip()
        if not scope_filter:
            return True
        patterns = [p.strip().lower() for p in scope_filter.split(",") if p.strip()]
        host_lower = host.lower()
        for pattern in patterns:
            if fnmatch.fnmatch(host_lower, pattern):
                return True
        return False

    def _get_base64_injected_value(self, param_value):
        """
        Detect if param_value (or its URL-decoded form) is base64-encoded text.
        If so, inject payload (using JSON injection if the decoded content is JSON,
        otherwise plain payload), re-encode to base64, and return the result.
        Returns None if not base64 or not useful text.
        """
        try:
            decoded_url = unquote(param_value)
            candidates = [decoded_url] if decoded_url != param_value else []
            candidates.append(param_value)
            for candidate in candidates:
                # Try standard then URL-safe base64
                for altchars in [None, b'-_']:
                    try:
                        padded = candidate + '=' * (-len(candidate) % 4)
                        if altchars:
                            raw = base64.b64decode(padded.replace('-', '+').replace('_', '/') + '=' * (-len(padded) % 4))
                        else:
                            raw = base64.b64decode(padded)
                        decoded_str = raw.decode('utf-8')
                        if not decoded_str.strip() or len(decoded_str) < 2:
                            continue
                        # Try JSON injection first, fall back to plain payload
                        json_injected = self._get_json_injected_value(decoded_str)
                        injected_str = json_injected if json_injected is not None else self.payload
                        re_encoded = base64.b64encode(injected_str.encode('utf-8'))
                        return re_encoded
                    except Exception:
                        continue
            return None
        except Exception:
            return None
    
    def _get_dynamic_path_segments(self, path):
        """
        Identify path segments that are likely dynamic (IDs, UUIDs, slugs with digits).
        Returns (all_segments, [(index, segment), ...]) where the second list contains
        only segments considered dynamic and safe to replace with the payload.
        """
        static_keywords = set([
            "api", "v1", "v2", "v3", "static", "assets", "admin", "auth",
            "login", "logout", "register", "signup", "search", "public",
            "private", "media", "images", "img", "js", "css", "fonts",
            "download", "upload", "export", "import", "graphql", "rest",
            "web", "app", "page", "pages", "home", "index", "about", "contact",
        ])
        segments = [s for s in path.split("/") if s]
        dynamic = []
        for i, seg in enumerate(segments):
            # Skip segments with file extensions (e.g. image.png, script.js)
            if "." in seg:
                continue
            seg_lower = seg.lower()
            if seg_lower in static_keywords:
                continue
            # Heuristic 1: pure numeric ID  (e.g. 12345)
            if re.match(r'^\d+$', seg):
                dynamic.append((i, seg))
                continue
            # Heuristic 2: UUID or long hex/token  (e.g. a1b2c3d4-... or 32+ hex chars)
            if re.match(r'^[0-9a-fA-F\-]{32,}$', seg):
                dynamic.append((i, seg))
                continue
            # Heuristic 3: slug that contains at least one digit (e.g. product-42, order_abc123)
            if re.match(r'^[a-zA-Z0-9_\-]{4,}$', seg) and re.search(r'\d', seg):
                dynamic.append((i, seg))
                continue
        return segments, dynamic

    def registerExtenderCallbacks(self, callbacks):
        self._callbacks = callbacks
        self._helpers = callbacks.getHelpers()
        callbacks.registerHttpListener(self)
        callbacks.setExtensionName("isXSS")
        callbacks.addSuiteTab(self)
        self._requestViewer = callbacks.createMessageEditor(self, False)
        self._responseViewer = callbacks.createMessageEditor(self, False)

        # Add Message Editors to UI in split pane for side-by-side view
        message_splitpane = JSplitPane(JSplitPane.HORIZONTAL_SPLIT)
        
        # Request panel
        request_panel = JPanel(BorderLayout())
        request_label = JLabel("Request")
        request_label.setFont(Font("Dialog", Font.BOLD, 12))
        request_panel.add(request_label, BorderLayout.NORTH)
        request_panel.add(self._requestViewer.getComponent(), BorderLayout.CENTER)
        
        # Response panel
        response_panel = JPanel(BorderLayout())
        response_label = JLabel("Response")
        response_label.setFont(Font("Dialog", Font.BOLD, 12))
        response_panel.add(response_label, BorderLayout.NORTH)
        response_panel.add(self._responseViewer.getComponent(), BorderLayout.CENTER)
        
        message_splitpane.setLeftComponent(request_panel)
        message_splitpane.setRightComponent(response_panel)
        message_splitpane.setResizeWeight(0.5)
        
        self.editor_panel.add(message_splitpane, BorderLayout.CENTER)


    def processHttpMessage(self, toolFlag, messageIsRequest, messageInfo):
        # Check if message received is a request or response
        if(messageIsRequest):
            # Ignore requests originated by this extension (prevents redirect loops)
            try:
                req_bytes = messageInfo.getRequest()
                if hasattr(self, '_helpers') and self._helpers and req_bytes is not None:
                    req_str = self._helpers.bytesToString(req_bytes)
                    if req_str in self.our_requests:
                        # remove it to avoid unbounded growth and ignore processing
                        try:
                            self.our_requests.discard(req_str)
                        except Exception:
                            pass
                        return
            except Exception:
                pass
            try:
                request = messageInfo.getRequest()
                request_data = self._helpers.analyzeRequest(messageInfo.getHttpService(), request)
                headers = request_data.getHeaders()
                method = request_data.getMethod()

                # Respect settings
                if method == "POST" and not self.settings.get("scan_post", True):
                    return
            
                # Get the parameters from the request
                parameters = request_data.getParameters()
                
                # Avoid testing duplicate URLs - create unique key from URL and method
                url = request_data.getUrl()

                # Filter out requests to Google and Google Tag Manager hosts
                try:
                    host = messageInfo.getHttpService().getHost().lower()
                except Exception:
                    try:
                        host = url.getHost().lower()
                    except Exception:
                        host = ""

                # Ignore analytics, tracking, and ad-serving domains
                _ignored_suffixes = (
                    "google.com",
                    "googletagmanager.com",
                    "googleapis.com",
                    "google-analytics.com",
                    "googlesyndication.com",
                    "googleadservices.com",
                    "doubleclick.net",
                    "facebook.com",
                    "facebook.net",
                    "fbcdn.net",
                    "analytics.yahoo.com",
                    "bing.com",
                    "bat.bing.com",
                    "scorecardresearch.com",
                    "hotjar.com",
                    "clarity.ms",
                    "segment.com",
                    "segment.io",
                    "mixpanel.com",
                    "amplitude.com",
                    "fullstory.com",
                    "newrelic.com",
                    "nr-data.net",
                    "cloudflareinsights.com",
                    "cdn.cookielaw.org",
                    "onetrust.com",
                )
                if any(host == s or host.endswith("." + s) for s in _ignored_suffixes):
                    return
                if "googletagmanager" in host or "google-analytics" in host:
                    return

                # Scope filter
                if not self._host_matches_scope(host):
                    return

                if self.settings.get("path_level_dedup", True):
                    url_key = host + "|" + str(url.getPath()) + "|" + method
                else:
                    url_key = str(url) + "|" + method
                if url_key in self.tested_urls:
                    return
                self.tested_urls.add(url_key)

                selected_cookie_param = None
                if self.settings.get("inject_cookie", False):
                    selected_cookie_param = self._pick_random_cookie_param(parameters)

                selected_header_name = None
                if self.settings.get("inject_header", False):
                    selected_header_name = self._pick_random_header_name(headers)

                # Headers with high probability of being reflected into HTML response body.
                # Chosen because servers commonly echo these into page content:
                #   Referer       -> "back to" links, breadcrumbs, analytics displays
                #   User-Agent    -> browser/device detection messages
                #   Accept-Language -> locale selection, language banners
                #   X-Forwarded-For -> "your IP is..." or debug output
                #   X-Forwarded-Host -> affects host-based URL generation embedded in HTML
                #   X-Original-URL  -> URL rewriting that gets echoed back into page
                #   X-Rewrite-URL   -> same as above on IIS/nginx setups
                _KNOWN_REFLECTION_HEADERS = [
                    "Referer", "User-Agent", "Accept-Language",
                    "X-Forwarded-For", "X-Forwarded-Host",
                    "X-Original-URL", "X-Rewrite-URL"
                ]
                selected_known_header = None
                if self.settings.get("inject_known_headers", True):
                    selected_known_header = random.choice(_KNOWN_REFLECTION_HEADERS)

                new_parameters = []
                
                # Loop over the parameters and modify as necessary
                for parameter in parameters:
                    # Skip cookie parameters - they should not be injected into the URL/body
                    if parameter.getType() == IParameter.PARAM_COOKIE:
                        continue
                    if(self.payload in parameter.getValue()):
                        return
                    new_value = self.payload
                    new_parameter = self._helpers.buildParameter(parameter.getName(), new_value, parameter.getType())
                    new_parameters.append(new_parameter)

                if not new_parameters and not selected_cookie_param and not selected_header_name:
                    return

                requests_to_test = []
                
                # Handle GET requests
                if method == "GET":
                    # Helper: rebuild the request reusing original headers (preserves Cookie etc.)
                    # Only the first header (request line) is replaced with the new path+query.
                    def build_get_request(path_and_query):
                        new_headers = list(headers)
                        new_headers[0] = method + " " + path_and_query + " HTTP/1.1"
                        return self._helpers.buildHttpMessage(new_headers, None)

                    # Standard / per-parameter request(s)
                    if self.settings.get("per_param_testing", False) and len(new_parameters) > 1:
                        # Per-param mode: one request per param; other params keep original values
                        for target_p in new_parameters:
                            pp_parts = []
                            for orig_p in parameters:
                                if orig_p.getType() == IParameter.PARAM_COOKIE:
                                    continue
                                if orig_p.getName() == target_p.getName():
                                    pp_parts.append(orig_p.getName() + '=' + quote(self.payload, safe=''))
                                else:
                                    pp_parts.append(orig_p.getName() + '=' + quote(orig_p.getValue(), safe='='))
                            pp_path = url.getPath() + "?" + '&'.join(pp_parts)
                            if url.getRef():
                                pp_path += "#" + url.getRef()
                            requests_to_test.append(build_get_request(pp_path))
                    elif new_parameters:
                        # All-at-once mode (default)
                        new_query = '&'.join([p.getName() + '=' + quote(p.getValue(), safe='=') for p in new_parameters])
                        path_query = url.getPath() + "?" + new_query
                        if url.getRef():
                            path_query += "#" + url.getRef()
                        requests_to_test.append(build_get_request(path_query))
                    else:
                        # If only header/cookie mutation is enabled, still test the original request
                        requests_to_test.append(request)
                    
                    # Nested value requests: for params whose value contains '=',
                    # also test with only the sub-value replaced (e.g. setck=cplng=payload)
                    for orig_param in parameters:
                        if orig_param.getType() == IParameter.PARAM_COOKIE:
                            continue
                        orig_value = orig_param.getValue()
                        if '=' in orig_value:
                            eq_idx = orig_value.index('=')
                            nested_new_value = orig_value[:eq_idx + 1] + self.payload
                            variant_params = []
                            for p in new_parameters:
                                if p.getName() == orig_param.getName():
                                    variant_params.append(self._helpers.buildParameter(p.getName(), nested_new_value, p.getType()))
                                else:
                                    variant_params.append(p)
                            variant_query = '&'.join([p.getName() + '=' + quote(p.getValue(), safe='=') for p in variant_params])
                            variant_path_query = url.getPath() + "?" + variant_query
                            if url.getRef():
                                variant_path_query += "#" + url.getRef()
                            requests_to_test.append(build_get_request(variant_path_query))

                    # JSON value requests: for GET params whose (URL-decoded) value is JSON,
                    # inject the payload into all string values inside the JSON structure.
                    if new_parameters:
                        for orig_param in parameters:
                            if orig_param.getType() == IParameter.PARAM_COOKIE:
                                continue
                            json_injected = self._get_json_injected_value(orig_param.getValue())
                            if json_injected is not None:
                                variant_parts = []
                                for p in new_parameters:
                                    if p.getName() == orig_param.getName():
                                        variant_parts.append(p.getName() + '=' + quote(json_injected, safe=''))
                                    else:
                                        variant_parts.append(p.getName() + '=' + quote(p.getValue(), safe='='))
                                json_path_query = url.getPath() + "?" + '&'.join(variant_parts)
                                if url.getRef():
                                    json_path_query += "#" + url.getRef()
                                requests_to_test.append(build_get_request(json_path_query))

                    # Base64 value requests: for GET params that are base64-encoded,
                    # inject the payload, re-encode, and test.
                    if new_parameters and self.settings.get("inject_base64", True):
                        for orig_param in parameters:
                            if orig_param.getType() == IParameter.PARAM_COOKIE:
                                continue
                            b64_injected = self._get_base64_injected_value(orig_param.getValue())
                            if b64_injected is not None:
                                variant_parts = []
                                for p in new_parameters:
                                    if p.getName() == orig_param.getName():
                                        variant_parts.append(p.getName() + '=' + quote(b64_injected, safe=''))
                                    else:
                                        variant_parts.append(p.getName() + '=' + quote(p.getValue(), safe='='))
                                b64_path_query = url.getPath() + "?" + '&'.join(variant_parts)
                                if url.getRef():
                                    b64_path_query += "#" + url.getRef()
                                requests_to_test.append(build_get_request(b64_path_query))

                    # Fragment hash injection: some server-side renderers and frameworks
                    # reflect or parse the URL fragment. Test with payload in the fragment.
                    frag_base = url.getPath()
                    orig_query = url.getQuery()
                    if new_parameters:
                        frag_base += "?" + '&'.join([p.getName() + '=' + quote(p.getValue(), safe='=') for p in new_parameters])
                    elif orig_query:
                        frag_base += "?" + orig_query
                    existing_frag = url.getRef()
                    # Variant 1: replace entire fragment with payload.
                    # Only fire if the request already has a fragment, or the
                    # "inject into all fragments" setting is enabled.
                    if existing_frag is not None or self.settings.get("inject_all_fragments", False):
                        requests_to_test.append(build_get_request(frag_base + "#" + quote(self.payload, safe='')))
                    # Variant 2: if existing fragment has key=value pairs, inject into each value
                    if existing_frag and '=' in existing_frag:
                        frag_parts = existing_frag.split('&')
                        injected_frag_parts = []
                        for fpart in frag_parts:
                            if '=' in fpart:
                                fname = fpart.split('=', 1)[0]
                                injected_frag_parts.append(fname + '=' + quote(self.payload, safe=''))
                            else:
                                injected_frag_parts.append(fpart)
                        requests_to_test.append(build_get_request(frag_base + "#" + '&'.join(injected_frag_parts)))

                    # Double-encoded variants: inject %22/%3E/%3C so a WAF sees encoded chars
                    # while a double-decoding backend receives the plain payload.
                    if new_parameters and self.settings.get("double_encode", False):
                        for orig_param in parameters:
                            if orig_param.getType() == IParameter.PARAM_COOKIE:
                                continue
                            de_parts = []
                            for p in new_parameters:
                                if p.getName() == orig_param.getName():
                                    de_parts.append(p.getName() + '=' + quote(self.payload_double_encoded, safe=''))
                                else:
                                    de_parts.append(p.getName() + '=' + quote(p.getValue(), safe='='))
                            de_path_query = url.getPath() + "?" + '&'.join(de_parts)
                            if url.getRef():
                                de_path_query += "#" + url.getRef()
                            requests_to_test.append(build_get_request(de_path_query))

                    # Path segment injection: replace dynamic segments (numeric IDs, UUIDs,
                    # slugs with digits) with the payload one at a time.
                    if self.settings.get("inject_path_segments", True):
                        path_segments, dynamic_segs = self._get_dynamic_path_segments(url.getPath())
                        for seg_idx, _orig_seg in dynamic_segs:
                            variant_segs = path_segments[:]
                            variant_segs[seg_idx] = quote(self.payload, safe='')
                            new_path = '/' + '/'.join(variant_segs)
                            orig_qs = url.getQuery()
                            ps_path_query = new_path + ('?' + orig_qs if orig_qs else '')
                            if url.getRef():
                                ps_path_query += '#' + url.getRef()
                            requests_to_test.append(build_get_request(ps_path_query))

                # Handle POST requests
                elif method == "POST":
                    if self.settings.get("per_param_testing", False) and len(new_parameters) > 1:
                        # Per-param mode: one request per parameter
                        for target_p in new_parameters:
                            per_param_req = request[:]
                            per_param_req = self._helpers.updateParameter(per_param_req, target_p)
                            requests_to_test.append(per_param_req)
                    else:
                        # All-at-once mode (default)
                        modified_request = request[:]
                        if new_parameters:
                            for param in new_parameters:
                                modified_request = self._helpers.updateParameter(modified_request, param)
                        requests_to_test.append(modified_request)

                    # JSON value variants for POST: inject payload into JSON-valued params
                    for orig_param in parameters:
                        if orig_param.getType() == IParameter.PARAM_COOKIE:
                            continue
                        json_injected = self._get_json_injected_value(orig_param.getValue())
                        if json_injected is not None:
                            json_request = request[:]
                            json_param = self._helpers.buildParameter(
                                orig_param.getName(), json_injected, orig_param.getType()
                            )
                            json_request = self._helpers.updateParameter(json_request, json_param)
                            requests_to_test.append(json_request)

                    # Base64 value variants for POST
                    if self.settings.get("inject_base64", True):
                        for orig_param in parameters:
                            if orig_param.getType() == IParameter.PARAM_COOKIE:
                                continue
                            b64_injected = self._get_base64_injected_value(orig_param.getValue())
                            if b64_injected is not None:
                                b64_request = request[:]
                                b64_param = self._helpers.buildParameter(
                                    orig_param.getName(), b64_injected, orig_param.getType()
                                )
                                b64_request = self._helpers.updateParameter(b64_request, b64_param)
                                requests_to_test.append(b64_request)

                    # Double-encoded variants for POST
                    if new_parameters and self.settings.get("double_encode", False):
                        for orig_param in parameters:
                            if orig_param.getType() == IParameter.PARAM_COOKIE:
                                continue
                            de_request = request[:]
                            de_param = self._helpers.buildParameter(
                                orig_param.getName(), self.payload_double_encoded, orig_param.getType()
                            )
                            de_request = self._helpers.updateParameter(de_request, de_param)
                            requests_to_test.append(de_request)

                else:
                    # Unsupported method
                    return
                
                for modified_request in requests_to_test:
                    # Optionally mutate one random cookie
                    if selected_cookie_param is not None:
                        try:
                            cookie_raw = selected_cookie_param.getValue()
                            # Prefer JSON injection, then base64, then plain payload
                            cookie_json = self._get_json_injected_value(cookie_raw)
                            if cookie_json is not None:
                                cookie_value = cookie_json
                            elif self.settings.get("inject_base64", True):
                                cookie_b64 = self._get_base64_injected_value(cookie_raw)
                                cookie_value = cookie_b64 if cookie_b64 is not None else self.payload
                            else:
                                cookie_value = self.payload
                            cookie_param = self._helpers.buildParameter(
                                selected_cookie_param.getName(),
                                cookie_value,
                                IParameter.PARAM_COOKIE
                            )
                            modified_request = self._helpers.updateParameter(modified_request, cookie_param)
                        except Exception:
                            pass

                    # Optionally mutate one random non-essential header
                    if selected_header_name:
                        modified_request = self._replace_header_value(
                            modified_request,
                            selected_header_name,
                            self.payload,
                            messageInfo.getHttpService()
                        )

                    # Inject into a known high-value reflection header (added if absent)
                    if selected_known_header:
                        modified_request = self._add_or_replace_header(
                            modified_request,
                            selected_known_header,
                            self.payload,
                            messageInfo.getHttpService()
                        )

                    # Mark this request as originating from us to avoid re-processing
                    try:
                        if hasattr(self, '_helpers') and self._helpers and modified_request is not None:
                            self.our_requests.add(self._helpers.bytesToString(modified_request))
                    except Exception:
                        pass

                    new_request = self._callbacks.makeHttpRequest(messageInfo.getHttpService(), modified_request)
                    # Analyze the request/response returned by makeHttpRequest
                    try:
                        new_request_data = self._helpers.analyzeRequest(new_request.getHttpService(), new_request.getRequest())
                    except Exception:
                        # Fallback: if analyzeRequest expects raw bytes (older API usage)
                        new_request_data = self._helpers.analyzeRequest(messageInfo.getHttpService(), modified_request)
                        
                    url = new_request_data.getUrl()

                    # Get the response to the new request
                    response = new_request.getResponse()
                    if not response:
                        # Silent fail - no need to spam console for network issues
                        continue
                        
                    response_data = self._helpers.analyzeResponse(response)

                    # Check if response is JSON (matches application/json and +json variants
                    # such as application/ld+json, application/vnd.api+json, application/hal+json)
                    resp_headers_for_ct = response_data.getHeaders()
                    is_json = any(
                        ("application/json" in h.lower().split(":", 1)[1] or "+json" in h.lower().split(":", 1)[1])
                        for h in resp_headers_for_ct
                        if ":" in h and h.lower().split(":", 1)[0].strip() == "content-type"
                    )

                    is_html = any(
                        "text/html" in h.lower().split(":", 1)[1]
                        for h in resp_headers_for_ct
                        if ":" in h and h.lower().split(":", 1)[0].strip() == "content-type"
                    )

                    # Only process HTML responses (and JSON if that setting is on).
                    # Skip JS, CSS, images, and other non-HTML content types.
                    if not is_html and not is_json:
                        continue

                    if is_json and not self.settings.get("detect_json", False):
                        continue

                    # Find response body and check if payload is reflected
                    response_body = response[response_data.getBodyOffset():]
                    if response_data.getBodyOffset() != -1:
                        reflected = []
                        response_body_str = self._helpers.bytesToString(response_body)
                        
                        if "ggg2\"" in response_body_str:
                            reflected.append("\"")
                        if "ggg3>" in response_body_str:
                            reflected.append(">")
                        if "ggg4<" in response_body_str:
                            reflected.append("<")
                        
                        # Check for DOM-based XSS sinks
                        dom_sinks = []
                        
                        # Payload marker anchors used across all sink checks.
                        # We require ggg2" (the literal first marker+char) to avoid matching
                        # any accidental occurrence of the substring "ggg" in page content.
                        P = r'ggg2"'

                        # 1. href attributes - payload must start the attribute value
                        if re.search(r'href\s*=\s*["\']?\s*' + P, response_body_str, re.IGNORECASE):
                            dom_sinks.append("href")
                        
                        # 2. Event handlers - payload must start the handler value
                        event_handlers = ['onclick', 'onload', 'onerror', 'onmouseover', 'onfocus',
                                        'onblur', 'onchange', 'onsubmit', 'onmouseout', 'onkeydown',
                                        'onkeyup', 'onkeypress', 'ondblclick', 'onmousedown', 'onmouseup']
                        for handler in event_handlers:
                            if re.search(handler + r'\s*=\s*["\']?\s*' + P, response_body_str, re.IGNORECASE):
                                dom_sinks.append(handler)
                                break
                        
                        # 3. Dangerous src/data attributes - payload must start the value
                        if re.search(r'<script[^>]+src\s*=\s*["\']?\s*' + P, response_body_str, re.IGNORECASE):
                            dom_sinks.append("script-src")
                        if re.search(r'<iframe[^>]+src\s*=\s*["\']?\s*' + P, response_body_str, re.IGNORECASE):
                            dom_sinks.append("iframe-src")
                        if re.search(r'<embed[^>]+src\s*=\s*["\']?\s*' + P, response_body_str, re.IGNORECASE):
                            dom_sinks.append("embed-src")
                        if re.search(r'<object[^>]+data\s*=\s*["\']?\s*' + P, response_body_str, re.IGNORECASE):
                            dom_sinks.append("object-data")
                        
                        # 4. JavaScript execution contexts - extract script block bodies
                        # and check for actual payload markers, avoiding false positives
                        # from "ggg" appearing anywhere in third-party scripts.
                        script_blocks = re.findall(r'<script[^>]*>(.*?)</script>', response_body_str, re.IGNORECASE | re.DOTALL)
                        if any('ggg2"' in blk or 'ggg3>' in blk for blk in script_blocks):
                            dom_sinks.append("script-context")
                        if re.search(r'\b(eval|setTimeout|setInterval)\s*\(\s*["\']?\s*' + P, response_body_str, re.IGNORECASE):
                            dom_sinks.append("js-exec")
                        
                        # 5. DOM manipulation - directly assigned
                        if re.search(r'\b(innerHTML|outerHTML)\s*=\s*["\']?\s*' + P, response_body_str, re.IGNORECASE):
                            dom_sinks.append("dom-write")
                        if re.search(r'document\.(write|writeln)\s*\(\s*["\']?\s*' + P, response_body_str, re.IGNORECASE):
                            dom_sinks.append("dom-write")
                        
                        # 6. URL/Navigation - directly assigned
                        if re.search(r'\b(location|location\.href)\s*=\s*["\']?\s*' + P, response_body_str, re.IGNORECASE):
                            dom_sinks.append("navigation")
                        if re.search(r'window\.open\s*\(\s*["\']?\s*' + P, response_body_str, re.IGNORECASE):
                            dom_sinks.append("navigation")
                        
                        # 7. Form action - payload must start the value
                        if re.search(r'<form[^>]+action\s*=\s*["\']?\s*' + P, response_body_str, re.IGNORECASE):
                            dom_sinks.append("form-action")
                        
                        tested_url_str = str(new_request_data.getUrl())
                        if reflected or dom_sinks:
                            if tested_url_str in self.reported_urls:
                                continue
                            self.reported_urls.add(tested_url_str)
                            # Format the reflected characters nicely
                            reflected_parts = []
                            if reflected:
                                reflected_parts.append(", ".join(reflected))
                            if dom_sinks:
                                reflected_parts.append("[DOM:" + ",".join(dom_sinks) + "]")

                            if is_json:
                                reflected_parts.append("[JSON]")
                            reflected_str = " ".join(reflected_parts) if reflected_parts else "(detected)"
                            row_tooltip = None
                            if is_json:
                                row_tooltip = "Content-Type: application/json is not vulnerable to XSS. Try to make the website render Content-Type: text/html"
                            self.data.append([self.id, new_request_data.getMethod(), str(new_request_data.getUrl()), reflected_str])
                            self.data_tooltips.append(row_tooltip)
                            self.id = self.id + 1
                            self.data_requests.append(modified_request)
                            self.data_responses.append(response)

                            # Update the JTable after updating the data
                            self.updateTable()
                        
            except Exception as e:
                # Log error quietly without stack trace for common issues
                error_msg = str(e)
                if "java.net" in error_msg or "connection" in error_msg.lower():
                    # Network errors are common, don't spam console
                    pass
                else:
                    # For unexpected errors, provide helpful message
                    print("[isXSS] Unexpected error - " + error_msg)
